#!/bin/sh
set -e

PKG="tophat-fusion"
VER="0.1.0"
PKG_DIR=/usr/lib/${PKG}${VER}

if [ "$1" = "configure" ]; then
    if [ ! -e /usr/bin/tophat-fusion ]; then
        for pathname in ${PKG_DIR}/bin/*; do
            filename=`basename $pathname`
            update-alternatives --install /usr/bin/${filename}-fusion ${filename} /usr/bin/${filename}${VER} 1
        done
    fi
fi
